name: Docker Image CI

on:
  workflow_run:
    workflows: ["Unit Testing"]
    types:
      - completed
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  runs-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image 🚢
        run: docker build . --file Dockerfile --tag sample:dev
